# Generated by Django 2.2.1 on 2019-06-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
